recursive: true
exit: true
spec: 'test/**/*.{js,ts}'
require:
  - tsx/esm
ignore:
  - 'test/examples/**'
  - 'test/lib/rest2-integration.*'
  - 'test/lib/transports/ws2-integration.*'
  - 'test/lib/ws2-subscriptions-integration.*'
